App/Modulos/Producto/controllers.py
#Importacion de Dependencias Flask
from flask import Blueprint, Flask, render_template, request, make_response, redirect,url_for,flash, jsonify
from App import db
# Importacion de modulo de ModeloProducto
from App.Modulos.Producto.model import productos
# Importacion de modulo de ModeloCategoria
from App.Modulos.Categoria.model import Categoria

#Inportacion de modulo de formularioCliente
from App.Modulos.Producto import form 
#
Producto=Blueprint('Productos',__name__,url_prefix='/Producto')

@Producto.route('/Productos', methods=['GET', 'POST'])  # registro de Productos
def Productos():
    frm = form.Fr_Productos(request.form)
    
    if request.method == 'POST':
        pr = productos.query.filter_by(Codigo=frm.Codigo.data).first()
        if frm.validate() and pr is None:
            dbproductos = productos(Codigo=frm.Codigo.data,
                                    nombre=frm.nombre.data,
                                    PrecioCompra=frm.P_U_C.data,
                                    PrecioVenta=frm.P_U_V.data,
                                    stock=0,
                                    Categoria=request.form['Categoria']
                                    )
            db.session.add(dbproductos)
            db.session.commit() 
            flash("Los datos an sido exitosamente Guardados")
            return redirect(url_for('Productos.Productos'))
        else:
            flash("Error: No se registrado con exito sus Datos.")
    return render_template('Producto/frProductos.html', frm=frm)
    
@Producto.route("/listaPr", methods=['GET','POST'])  # listado de productos.
def listaPr():

    titulo = "Listado de Productos"
    listas = db.session.query(Categoria.Nombre,productos.nombre,productos.PrecioCompra,productos.PrecioVenta,productos.stock).join(productos).all()
    for i in listas:
        print(i)
    return render_template("Producto/listaPr.html", titulo=titulo, listas=listas)


@Producto.route("/UpdatePr", methods=['POST'])
def UpdatePr():
    update = productos.query.filter_by(Codigo=request.form['Codigo']).first()
    update.nombre = request.form['nombre']
    update.PrecioCompra = request.form['P_U_C']
    update.PrecioVenta = request.form['P_U_V']
    db.session.commit()
    return redirect(url_for('Productos.listaPr'))

@Producto.route('/deletePr',methods=['POST'])
def deletePr():
    print(request.form)
    dlete = productos.query.filter_by(Codigo=request.form['Codigo']).first()
    db.session.delete(dlete)
    db.session.commit()
    return redirect(url_for('Productos.listaPr'))

@Producto.route("/modalPr")
def modalPr():
    frm = form.Fr_Productos(request.form)
    return render_template("modal/modalproducto.html", frm=frm, title="Producto")

App/Modulos/Proveedor/controllers.py
#Importacion de Dependencias Flask
from flask import Blueprint,Flask, render_template, request,redirect,url_for,flash
#modelado de basedato.
from App import db
# Importacion de modulo de ModeloCliente
from App.Modulos.Proveedor.model import Proveedor
#Inportacion de modulo de formularioCliente
from App.Modulos.Proveedor import form

_Proveedor=Blueprint('Proveedor',__name__,url_prefix='/Proveedor')

@_Proveedor.route('/Proveedor', methods=['GET', 'POST'])  # registro de proveedor
def proveedor():
    frm = form.Fr_Proveedor(request.form)
    if request.method == 'POST':
        pr = Proveedor.query.filter_by(CI=frm.CI.data).first()
        if frm.validate() and pr is None:
            new_user = Proveedor(razonSolcial=frm.RasonSocial.data,
                                 CI=frm.CI.data,
                                 Direccion=frm.Direccion.data,
                                 Correo=frm.Correo.data,
                                 convencional=frm.Convencional.data,
                                 Celular=frm.Celular.data
                                )
            db.session.add(new_user)
            db.session.commit()
            flash("Se registrado con exito sus datos")
            return redirect(url_for('Proveedor.proveedor'))
        else:
            flash("Error: No se registrado con exito sus Datos")
    return render_template('Proveedor/frproveedor.html', frm=frm)

@_Proveedor.route('/listaP')  # listado de Proveedores.
def listaP():
    titulo = "Lista Proveedor"
    return render_template("Proveedor/listaP.html", titulo=titulo, listas=Proveedor.query.all())

@_Proveedor.route('/UpdateP', methods=[ 'POST'])
def UpdateP():
    print(request.form)

    updateP = Proveedor.query.filter_by(CI=request.form['CI']).first()
    print("ci:",updateP.CI)
    updateP.razonSolcial = request.form['RasonSocial']
    updateP.Direccion = request.form['Direccion']
    updateP.Correo = request.form['Correo']
    updateP.convencional= request.form['Convencional']
    updateP.Celular = request.form['Celular']
    db.session.commit()
    return redirect(url_for('Proveedor.listaP'))


@_Proveedor.route('/deleteP/<string:id>',methods=['GET','POST'])
def deleteP(id=None):
    dlTP = Proveedor.query.filter_by(CI=id).first()
    db.session.delete(dlTP) 
    db.session.commit()
    return redirect(url_for('Proveedor.listaP'))

@_Proveedor.route("/modalP")
def modalP():
    frm = form.Fr_Proveedor(request.form)
    return render_template("modal/modaproveedor.html", frm=frm, title="Proveedor")

App/templates/modal/modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">First</th>
                  <th scope="col">Last</th>
                  <th scope="col">Handle</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                <tr>
                  <th scope="row">3</th>
                  <td>Larry</td>
                  <td>the Bird</td>
                  <td>@twitter</td>
                </tr>
              </tbody>
            </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

App/templates/modal/modalalmacen.html
{%from '_macro.html' import render_field %}

<div  id="modalalmacen" class="modal" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title">Movimientos de Ingreso </h3>
      </div>

      <div class="modal-body">

        <table>
          <thead>
            <tr>
            <th>fechaIngreso</th>
          </tr>
          </thead>

          <tbody>
            
            {%for dato in datos%}
             <tr>
               <td>{{dato.fecha_ingreso}} </td>
              </tr>
             {%endfor%}



          </tbody>
        </table>

        </div>
      <div class="modal-footer">
        <button  class="btn btn-info" type="submit" id="enviar" >Guardar Cambios</button>  
        <a   class="btn btn-warning" type="submit" id="Eliminar" >Eliminar</a> 
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

App/templates/modal/modalcliente.html
{%from '_macro.html' import render_field %}

<div  id="modalCliente" class="modal" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>0
        </button>
        <h3 class="modal-title">Actualizar {{title}}</h3>
      </div>

      <div class="modal-body">

        <form  action=" {{ url_for('Update') }}" method="POST">
          
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
       
          <div class="form-group">
            {{ render_field (frm.id,class='form-control col-md-2') }}
          </div>
       
          <div class="form-group">
            {{render_field(frm.Nombre,class='form-control col-md-2')}}
          </div>
       
          <div class="form-group">
            {{render_field(frm.Apellido,class='form-control col-md-2')}}
          </div>

          <div class="form-group">
            {{render_field(frm.FechaNacimiento,class='form-control')}}
          </div>       
        </form>
        </div>
      <div class="modal-footer">
        <button  class="btn btn-info" type="submit" id="enviar" >Guardar Cambios</button>  
        <a   class="btn btn-warning" type="submit" id="Eliminar" >Eliminar</a> 
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

App/templates/modal/modalproducto.html
{%from '_macro.html' import render_field %}
<div  id="modalProducto" class="modal" role="dialog" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h3 class="modal-title">Actualizar {{title}}</h3>
        </div>

          <form  method="POST"  >
           
            <div class="modal-body">           
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />  
            <div class="form-group">
              {{ render_field (frm.Codigo,class='form-control col-md-2',disabled='') }}
            </div>    

            <div class="form-group">
              {{render_field(frm.nombre,class='form-control col-md-2')}}
            </div>  

            <div class="form-group">
              {{render_field(frm.P_U_C,class='form-control col-md-2')}}
            </div>

            <div class="form-group">
              {{render_field(frm.P_U_V,class='form-control')}}
            </div>

            <div class="modal-footer">
              <button class="btn btn-info" type="submit" id="enviar" formaction="{{url_for('Productos.UpdatePr')}}">Guardar Cambios</button>  
              <button type="submit" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
            
        </div>
      </form>

      </div>
    </div>
  </div>

App/templates/modal/modaproveedor.html
{%from '_macro.html' import render_field %}
<div  id="modalProveedor" class="modal" role="dialog" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h3 class="modal-title">Actualizar {{title}}</h3>
        </div>

        <form  method ="POST" action="{{ url_for('Proveedor.UpdateP')}}">
          <div class="modal-body">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />   
          
            <div class="form-group"> 
              {{ render_field(frm.RasonSocial,class= 'form-control  col-md-2') }}
              </div>

            <div class="form-group">
              {{ render_field (frm.CI,class='form-control col-md-2') }}
            </div>   

            <div class="form-group">
              {{render_field(frm.Direccion,class='form-control col-md-2')}}
            </div>   

            <div class="form-group">
              {{render_field(frm.Correo,class='form-control col-md-2')}}
            </div>

            <div class="form-group">
              {{render_field(frm.Convencional,class='form-control')}}
            </div>
            <div class="form-group">
                {{ render_field(frm.Celular,class='form-control') }}
              </div>
          </div>

          <div class="modal-footer">
          <button type="submit" class="btn btn-info" id="enviar" >Guardar Cambios</button>  
          <a type='submit' class="btn btn-warning" id="Eliminar" >Eliminar</a> 
          <button  type='submit' class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>

      </form>

      </div>
    </div>
  </div>